version: '3.9'

services:
    mongo:
        image: mongo:5.0.5
        container_name: mongo
        restart: unless-stopped
        networks:
            - mess
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

    mongo-express:
        image: mongo-express:1.0.0-alpha
        container_name: mongo-express
        restart: unless-stopped
        depends_on:
            - mongo
        networks:
            - mess
        ports:
            - 8080:8081
        environment:
            ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo:27017
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}

    mess-api:
        build:
            context: .
        container_name: mess-api
        restart: unless-stopped
        depends_on:
            - mongo
        networks:
            - mess
        ports:
            - ${PORT}:${PORT}
        environment:
            MONGO_APP_NAME: ${MONGO_APP_NAME}
            MONGO_USER: ${MONGO_USER}
            MONGO_PASSWORD: ${MONGO_PASSWORD}
            MONGO_URI: mongodb://mongo:27017
            PORT: ${PORT}

networks:
    mess:
        driver: bridge